spring:
  application:
    name: ribbon-client

server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/

stores:
  ribbon:
    listOfServers: example.com, kevin, google.com

ribbon:
  eureka:
    enabled: false #配置禁止调用eureka-client获取注册列表，ribbon通过stores.ribbon.listOfServers来配置服务实例url , 默认为true-默认通过eureka-client获取注册列表

