eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
server:
  port: 5001
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9400
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service