eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
server:
  port: 9401
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9400
  sleuth:
    sampler:
      percentage: 1.0
