spring:
  application:
    name: eureka-feign-client

server:
  port: 8767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/

feign:
  hystrix:
    enabled: true  #feign 起步依赖hystrix熔断器, 通过该配置打开熔断

