spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native

  application:
    name: config-server
server:
  port: 8900
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/